// ── Barrel: re-export everything (pages import from '../api/client') ──
export * from './types'
export * from './http'
export * from './services'
export * from './hosts'
export * from './profiles'
export * from './events'
export * from './audit'
export * from './files'
export * from './leases'
export * from './settings'
export * from './logs'
export * from './netboot'
export * from './answerTemplates'
export * from './installTasks'
export * from './dns'
export * from './access'
export * from './bmc'
export * from './dhcp'
export * from './wol'
export * from './osimages'
export * from './network'
export * from './bootloader'
export * from './version'
export * from './baselines'
export * from './store'

import { getMetrics, getStatus } from './services'
import { createHost, deleteHost, getHost, getHostBootConfig, getHosts, powerHost, updateHost, wakeHost } from './hosts'
import { createProfile, createProfileFromNetboot, deleteProfile, getProfiles, getScriptDiff, getScriptVersion, getScriptVersions, rollbackScriptVersion, updateProfile } from './profiles'
import { getEvents } from './events'
import { getAuditLogs } from './audit'
import { deleteFile, getBootRootDir, getFiles, uploadFile } from './files'
import { batchDeleteLeases, deleteLease, getLeases, getLeaseStats, pruneLeases } from './leases'
import {
  browseNFSPath,
  getArchMap,
  getArchMapDefaults,
  getDHCPSettings,
  getDNSSettings,
  getGeneralSettings,
  getIPXEScript,
  getInterfaceSettings,
  getInterfaces,
  getNFSSettings,
  getNetbootSettings,
  getSettings,
  getTFTPSettings,
  updateArchMap,
  updateDHCPSettings,
  updateDNSSettings,
  updateGeneralSettings,
  updateIPXEScript,
  updateInterfaceSettings,
  updateNFSSettings,
  updateNetbootSettings,
  updateSettings,
  updateTFTPSettings,
  validateNFSPath,
} from './settings'
import { cleanupLogs, getLogDiskUsage, getLogFiles, getLoggingSettings, updateLoggingSettings } from './logs'
import {
  deleteNetbootOverlay,
  getNetbootCatalog,
  getNetbootDistro,
  getNetbootFileStatus,
  getNetbootGroups,
  getNetbootOverlay,
  getNetbootOverlays,
  upsertNetbootOverlay,
} from './netboot'
import {
  createAnswerTemplate,
  deleteAnswerTemplate,
  getAnswerTemplate,
  getAnswerTemplatePresets,
  getAnswerTemplateVersion,
  getAnswerTemplateVersions,
  getAnswerTemplates,
  previewAnswerTemplate,
  rollbackAnswerTemplate,
  updateAnswerTemplate,
  validateAnswerTemplate,
  validateAnswerTemplateById,
} from './answerTemplates'
import { createInstallTask, deleteInstallTask, getInstallTask, getInstallTasks, updateInstallTask } from './installTasks'
import { createDNSRecord, deleteDNSRecord, getDNSRecord, getDNSRecords, updateDNSRecord } from './dns'
import {
  addUnauthorizedToBlacklist,
  addUnauthorizedToWhitelist,
  createBlacklistEntry,
  createWhitelistEntry,
  deleteBlacklistEntry,
  deleteUnauthorizedDevice,
  deleteWhitelistEntry,
  getBlacklist,
  getUnauthorizedDevices,
  getWhitelist,
} from './access'
import {
  bmcBatchPowerOff,
  bmcBatchPowerOn,
  bmcBatchRestart,
  bmcBatchStatus,
  bmcImportCSV,
  bmcPowerOff,
  bmcPowerOn,
  bmcPowerStatus,
  bmcRestart,
  bmcSetBootDevice,
  createBMCConfig,
  deleteBMCConfig,
  getBMCConfig,
  getBMCConfigs,
  probeBMC,
  refreshBMCConfig,
  updateBMCConfig,
} from './bmc'
import {
  createDHCPReservation,
  deleteDHCPReservation,
  getDHCPReservation,
  getDHCPReservations,
  updateDHCPReservation,
} from './dhcp'
import {
  batchWakeHosts,
  createWOLSchedule,
  deleteAllWOLHistory,
  deleteWOLHistory,
  deleteWOLSchedule,
  getWOLHistory,
  getWOLHistoryByMAC,
  getWOLInterfaces,
  getWOLSchedules,
} from './wol'
import { deleteOSImage, extractOSImage, getOSImage, getOSImages, importOSImages, browseFs, mountOSImage, reprocessOSImage, unmountOSImage, updateOSImage, uploadOSImage, uploadOSImageWithProgress } from './osimages'
import { getNetworkInterfaces, networkPing, networkPingStream, networkTraceroute, networkTracerouteStream } from './network'
import { checkBootloaderFile, getBootloaderCheck, getBootloaderFiles } from './bootloader'
import { getBaselines, getBaseline, createBaseline, updateBaseline, deleteBaseline, getBaselineScripts, getBaselineScript, upsertBaselineScript, deleteBaselineScript } from './baselines'
import { getStoreCatalog, getStoreItem, importStoreItem } from './store'
import { batchService, getServices, restartService, startService, stopService, updateAutoStart } from './services'

// ── Convenience namespace (backward-compat) ──
export const api = {
  getStatus,
  getMetrics,
  getHosts,
  getHost,
  getHostBootConfig,
  batchWakeHosts,
  getWOLHistory,
  getWOLHistoryByMAC,
  deleteWOLHistory,
  deleteAllWOLHistory,
  createWOLSchedule,
  getWOLSchedules,
  deleteWOLSchedule,
  getWOLInterfaces,
  getOSImages,
  getOSImage,
  uploadOSImage,
  uploadOSImageWithProgress,
  deleteOSImage,
  extractOSImage,
  reprocessOSImage,
  updateOSImage,
  importOSImages,
  browseFs,
  mountOSImage,
  unmountOSImage,
  createHost,
  updateHost,
  deleteHost,
  wakeHost,
  powerHost,
  getProfiles,
  createProfile,
  updateProfile,
  deleteProfile,
  createProfileFromNetboot,
  getEvents,
  getAuditLogs,
  getFiles,
  uploadFile,
  deleteFile,
  getBootRootDir,
  getLeases,
  getLeaseStats,
  deleteLease,
  batchDeleteLeases,
  pruneLeases,
  getSettings,
  updateSettings,
  getInterfaces,
  getNetbootCatalog,
  getNetbootGroups,
  getNetbootDistro,
  getNetbootFileStatus,
  getNetbootOverlays,
  getNetbootOverlay,
  upsertNetbootOverlay,
  deleteNetbootOverlay,
  getAnswerTemplates,
  createAnswerTemplate,
  getAnswerTemplate,
  updateAnswerTemplate,
  deleteAnswerTemplate,
  validateAnswerTemplate,
  validateAnswerTemplateById,
  previewAnswerTemplate,
  getAnswerTemplatePresets,
  getAnswerTemplateVersions,
  getAnswerTemplateVersion,
  rollbackAnswerTemplate,
  getInstallTasks,
  createInstallTask,
  getInstallTask,
  getDNSRecords,
  getDNSRecord,
  createDNSRecord,
  updateDNSRecord,
  deleteDNSRecord,
  updateInstallTask,
  deleteInstallTask,
  getServices,
  startService,
  stopService,
  restartService,
  batchService,
  updateAutoStart,
  getBlacklist,
  createBlacklistEntry,
  deleteBlacklistEntry,
  getWhitelist,
  createWhitelistEntry,
  deleteWhitelistEntry,
  getUnauthorizedDevices,
  addUnauthorizedToWhitelist,
  addUnauthorizedToBlacklist,
  deleteUnauthorizedDevice,
  getGeneralSettings,
  updateGeneralSettings,
  getInterfaceSettings,
  updateInterfaceSettings,
  getDHCPSettings,
  updateDHCPSettings,
  getTFTPSettings,
  updateTFTPSettings,
  getArchMap,
  updateArchMap,
  getArchMapDefaults,
  getIPXEScript,
  updateIPXEScript,
  getDNSSettings,
  updateDNSSettings,
  getNFSSettings,
  updateNFSSettings,
  validateNFSPath,
  browseNFSPath,
  getNetbootSettings,
  updateNetbootSettings,
  getLoggingSettings,
  updateLoggingSettings,
  getLogFiles,
  getLogDiskUsage,
  cleanupLogs,
  getBMCConfigs,
  getBMCConfig,
  createBMCConfig,
  updateBMCConfig,
  deleteBMCConfig,
  probeBMC,
  refreshBMCConfig,
  bmcPowerOn,
  bmcPowerOff,
  bmcRestart,
  bmcPowerStatus,
  bmcSetBootDevice,
  bmcBatchPowerOn,
  bmcBatchPowerOff,
  bmcBatchRestart,
  bmcBatchStatus,
  bmcImportCSV,
  getDHCPReservations,
  getDHCPReservation,
  createDHCPReservation,
  updateDHCPReservation,
  deleteDHCPReservation,
  networkPing,
  networkPingStream,
  networkTraceroute,
  networkTracerouteStream,
  getNetworkInterfaces,
  getBootloaderCheck,
  getBootloaderFiles,
  checkBootloaderFile,
  getScriptVersions,
  getScriptVersion,
  getScriptDiff,
  rollbackScriptVersion,
  getBaselines,
  getBaseline,
  createBaseline,
  updateBaseline,
  deleteBaseline,
  getBaselineScripts,
	  getBaselineScript,
	  upsertBaselineScript,
	  deleteBaselineScript,
	  getStoreCatalog,
	  getStoreItem,
	  importStoreItem,
	}
