package api

// Baseline pull exec-bundle + answer-file injection helpers.
//
// 自动应答模板只需要“几条固定命令”就能在安装后把该主机配置的初始化基线拉下来执行。
// 平台侧提供两类可直接执行的聚合产物，供应答钩子引用：
//   GET /api/v1/baselines/pull.sh  — POSIX sh，逐个执行 type=shell 的脚本
//   GET /api/v1/baselines/pull.ps1 — PowerShell，逐个执行 type=powershell 的脚本
// 身份按 global.identity_attr 取 mac 或 sn；无配置一律空产物（exit 0），不影响安装。

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/pxelab/pxelab/internal/config"
)

const baselinePullMarker = "pxelab-baseline-pull"

// 内置默认钩子模板。{{URL}} 在注入时替换为聚合产物地址（pull.sh / pull.ps1）。
// 与 global.baseline_hooks 配置一一对应；配置留空即用这里的默认值。
const (
	defaultKickstartHook = `%post --interpreter=/bin/bash
# PxeLab baseline pull (pxelab-baseline-pull)
set +e
if command -v curl >/dev/null 2>&1; then curl -fsSL '{{URL}}' | bash
elif command -v wget >/dev/null 2>&1; then wget -qO- '{{URL}}' | bash
fi
%end`

	defaultPreseedHook = `in-target sh -c "if command -v curl >/dev/null 2>&1; then curl -fsSL '{{URL}}' | sh; else wget -qO- '{{URL}}' | sh; fi" || true`

	defaultSubiquityHook = `late-commands:
  - sh -c "curl -fsSL '{{URL}}' | sh || true"`

	defaultAutoUnattendHook = `powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "try { $u='{{URL}}'; (New-Object Net.WebClient).DownloadString($u) | Invoke-Expression } catch {}"`
)

// DefaultBaselineHooks 返回内置默认钩子模板（供设置页展示/重置）。
func DefaultBaselineHooks() config.BaselineHooksConfig {
	return config.BaselineHooksConfig{
		Kickstart:    defaultKickstartHook,
		Preseed:      defaultPreseedHook,
		Subiquity:    defaultSubiquityHook,
		AutoUnattend: defaultAutoUnattendHook,
	}
}

// renderHook 用 url 替换模板中的 {{URL}}；tpl 为空时用 fallback 默认模板。
func renderHook(tpl, fallback, url string) string {
	if strings.TrimSpace(tpl) == "" {
		tpl = fallback
	}
	return strings.ReplaceAll(tpl, "{{URL}}", url)
}

// identityParam 按配置的身份键生成查询参数（mac/sn）。
func (h *BaselineHandler) identityParam(mac, sn string) string {
	if h.identityAttr == "sn" {
		return "sn=" + sn
	}
	return "mac=" + mac
}

// PullShellScript 输出一段可直接 `| sh` 执行的脚本：按序运行该主机的 shell 基线。
func (h *BaselineHandler) PullShellScript(w http.ResponseWriter, r *http.Request) {
	host, found := h.resolveHost(r)
	if !found {
		w.Header().Set("Content-Type", "text/x-shellscript; charset=utf-8")
		w.Write([]byte("#!/bin/sh\nexit 0\n"))
		return
	}
	scripts, err := h.collectScripts(r.Context(), host, "shell")
	if err != nil {
		Error(w, http.StatusInternalServerError, err.Error())
		return
	}
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# generated by PxeLab " + baselinePullMarker + "\n")
	for i, sc := range scripts {
		fmt.Fprintf(&b, "\ncat > /tmp/pxelab-init-%d.sh <<'PXEBL'\n%s\nPXEBL\n", i, sc.Content)
		fmt.Fprintf(&b, "sh /tmp/pxelab-init-%d.sh || echo '[pxelab] script failed (non-fatal): %s'\n", i, sc.Name)
	}
	w.Header().Set("Content-Type", "text/x-shellscript; charset=utf-8")
	w.Write([]byte(b.String()))
}

// PullPowerShellScript 输出一段可直接执行的 PowerShell：按序运行该主机的 powershell 基线。
func (h *BaselineHandler) PullPowerShellScript(w http.ResponseWriter, r *http.Request) {
	host, found := h.resolveHost(r)
	if !found {
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.Write([]byte("# no baseline\n"))
		return
	}
	scripts, err := h.collectScripts(r.Context(), host, "powershell")
	if err != nil {
		Error(w, http.StatusInternalServerError, err.Error())
		return
	}
	var b strings.Builder
	b.WriteString("# generated by PxeLab " + baselinePullMarker + "\n")
	for _, sc := range scripts {
		fmt.Fprintf(&b, "\ntry {\n# ---- %s ----\n%s\n} catch { Write-Warning ('[pxelab] script failed (non-fatal): ' + $_.Exception.Message) }\n", sc.Name, sc.Content)
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Write([]byte(b.String()))
}

// buildPullURL 生成应答模板注入时使用的聚合产物 URL。
func buildPullURL(baseURL, execExt, identityParam string) string {
	return fmt.Sprintf("http://%s/api/v1/baselines/pull.%s?%s", baseURL, execExt, identityParam)
}

// augmentBaselinePull 在渲染后的应答文件上追加/合并“拉取并执行基线”的钩子。
// 返回注入后的内容；applied=false 表示该类型暂时无法安全注入（调用方应告警）。
// 幂等：内容已含标记则跳过。
// hooks 为 global.baseline_hooks 自定义模板，空字段回落到内置默认。
func augmentBaselinePull(content, answerType, baseURL, mac, sn string, hooks config.BaselineHooksConfig) (string, bool) {
	if strings.Contains(content, baselinePullMarker) {
		return content, true
	}
	// 同时带上可用身份键；/baselines/pull.{sh,ps1} 按 global.identity_attr 取用其一
	parts := []string{}
	if mac != "" {
		parts = append(parts, "mac="+mac)
	}
	if sn != "" {
		parts = append(parts, "sn="+sn)
	}
	if len(parts) == 0 {
		return content, false // 无可用身份，跳过注入
	}
	ip := strings.Join(parts, "&")
	shURL := buildPullURL(baseURL, "sh", ip)
	psURL := buildPullURL(baseURL, "ps1", ip)

	switch answerType {
	case "preseed", "subiquity":
		return augmentLinuxPreseed(content, shURL, hooks)
	case "kickstart":
		return augmentKickstart(content, shURL, hooks)
	case "autounattend":
		return augmentAutoUnattend(content, psURL, hooks)
	default:
		return content, false
	}
}

// augmentLinuxPreseed 覆盖 debian-installer preseed 与 Ubuntu subiquity(autoinstall, YAML)。
func augmentLinuxPreseed(content, shURL string, hooks config.BaselineHooksConfig) (string, bool) {
	block := ""
	switch {
	case strings.Contains(content, "d-i preseed/late_command string"):
		// 已有 late_command：合并为一条链（preseed 同一 key 重复时后者覆盖前者）
		lines := strings.Split(content, "\n")
		var kept []string
		var existing []string
		for _, ln := range lines {
			trim := strings.TrimSpace(ln)
			if strings.HasPrefix(trim, "d-i preseed/late_command string") {
				existing = append(existing, strings.TrimSpace(strings.TrimPrefix(trim, "d-i preseed/late_command string")))
				continue
			}
			kept = append(kept, ln)
		}
		all := append(existing, renderHook(hooks.Preseed, defaultPreseedHook, shURL))
		block = "d-i preseed/late_command string " + strings.Join(all, " && ")
		content = strings.Join(kept, "\n")
	case strings.Contains(content, "late-commands:"):
		// subiquity：已有 late-commands 列表时无法安全插入，交由人工确认（返回未注入）
		return content, false
	default:
		block = renderHook(hooks.Subiquity, defaultSubiquityHook, shURL)
	}
	return content + "\n# PxeLab baseline pull (" + baselinePullMarker + ")\n" + block + "\n", true
}

// augmentKickstart 在末尾追加 %post 段（anaconda 允许多个 %post）。
func augmentKickstart(content, shURL string, hooks config.BaselineHooksConfig) (string, bool) {
	return content + "\n" + renderHook(hooks.Kickstart, defaultKickstartHook, shURL) + "\n", true
}

// augmentAutoUnattend 在 oobeSystem 的 Microsoft-Windows-Shell-Setup 组件里注入 FirstLogonCommands。
func augmentAutoUnattend(content, psURL string, hooks config.BaselineHooksConfig) (string, bool) {
	if !strings.Contains(content, "oobeSystem") || !strings.Contains(content, "Microsoft-Windows-Shell-Setup") {
		return content, false
	}
	if strings.Contains(content, "<FirstLogonCommands") {
		return content, false // 已有 FirstLogonCommands：请人工合并
	}
	// 模板渲染后再做 XML 转义
	cmd := xmlEscape(renderHook(hooks.AutoUnattend, defaultAutoUnattendHook, psURL))
	snippet := "\n<FirstLogonCommands>\n<SynchronousCommand wcm:action=\"add\">\n<CommandLine>" + cmd +
		"</CommandLine>\n<Description>PxeLab baseline pull</Description>\n<Order>1</Order>\n</SynchronousCommand>\n</FirstLogonCommands>"

	// 定位组件开标签结束处，紧跟其后插入
	idx := strings.Index(content, `<component name="Microsoft-Windows-Shell-Setup"`)
	if idx < 0 {
		return content, false
	}
	gt := strings.Index(content[idx:], ">")
	if gt < 0 {
		return content, false
	}
	pos := idx + gt + 1
	return content[:pos] + snippet + content[pos:], true
}

func xmlEscape(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;")
	return r.Replace(s)
}
